import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#1A1A1A",
  }, 
  header: {
    width: "100%",
    height: 173,
    backgroundColor: "#0D0D0D",
    flexDirection: "column",
    padding: 24,
  }, 
  image: {
    marginTop: 50,
    justifyContent: "center",
    alignItems: "center",
  },
  headerContent: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center", 
    marginTop: 60, 
  }, 
  input: {
    flex: 1,
    height: 54,
    backgroundColor: "#262626",
    borderRadius: 5,
    color: "#FFF",
    padding: 16,
    fontSize: 16,
    marginRight: 4,
  },
  button: {
    borderRadius: 5,
    backgroundColor: "#1E6F9F",
    width: 52,
    height: 52,
    alignItems: "center",
    justifyContent: "center",
  },
  buttonText: {
    color: "#FFF",
    fontSize: 16,
  }, 
  contentList: { 
    height: 691,
    marginTop: 38,
  },
  sectionState: {
    maxWidth:'100%',
    height: 17,
    justifyContent: "space-between",
    flexDirection: "row",
    marginTop: 39,
  },
  textStyle: { 
    fontSize:14,
    color: "#4EA8DE", 
  },
  taskMarkerDone: { 
    height: 16,
    width: 16,
    borderRadius: 9,
    backgroundColor: "#5E60CE",
    marginRight: 15,
    alignItems: "center",
    justifyContent: "center",
  },
  taskMarker: { 
    height: 16,
    width: 16,
    borderRadius: 9,
    borderWidth: 1,
    borderColor: "#4EA8DE",
    marginRight: 15,
    alignItems: "center",
    justifyContent: "center", 
  },
  taskTextDone: {
    color: "#5E60CE",
    textDecorationLine: "line-through",
    fontFamily: "Inter-Medium",
  },
  numberSection:{
    marginLeft: 8,
    backgroundColor:"#333", 
    borderRadius:9
  },
  numberStyle: { 
    padding:2,
    width: 25,
    height: 19,
    color: "#FFF", 
    justifyContent:'center',
    textAlign:"center",
    alignItems:'center',
    fontSize:12, 
  }, 
  counterStyle: { 
    flexDirection: "row", 
  },
  textStyle2: { 
    color: "#8284FA", 
    fontSize:14,
  },
  separator: {
    height: 1,
    backgroundColor: "#333333",
    marginTop: 21,
  }, 
  box: {
    borderRadius: 8,
    width: "100%",
    height: 64,
    backgroundColor: "#333333",
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    alignContent: "center",
    marginTop: 20,
  },
  icon: {
    justifyContent: "center",
    alignItems: "center",
    height: 17,
    width: 17,
    marginLeft: 8,
  },
  card: {
    width: 235,
    height: 40,
    justifyContent: "center",
    alignItems: "center",
    textAlign: "center",
  },
  textBox: {
    color: "#FFFFFF",
    fontSize: 15,
  }, 
  icon2: {
    justifyContent: "center",
    alignItems: "center",
    height: 14,
    width: 12,
    marginRight: 8,
  },
  imageStyle: {
    justifyContent: "center",
    alignItems: "center",
    marginTop: 48,
  },
  listEmptyText: {
    marginTop: 16,
    fontWeight: "bold",
    color: "#808080",
    fontSize: 14,
    textAlign: "center",
  },
  listEmptyText2: {
    color: "#808080",
    fontSize: 14,
    textAlign: "center",
  },
});
